- name: learning blocks
  hosts: all
  tasks:
    - name: Attempt and graceful roll back demo
      block:
        - name: Print a message
          ansible.builtin.debug:
            msg: 'I execute normally'
          changed_when: true
          notify: Run me even after an error
          # Goes to rescue section
        - name: Force a failure
          ansible.builtin.command: /bin/false

        - name: Never print this
          ansible.builtin.debug:
            msg: 'I never execute, due to the above task failing, :-('
      # Only executed when task(s) fails. Like Catch block in python
      rescue:
        - name: Print when errors
          ansible.builtin.debug:
            msg: 'I caught an error'

        - name: Force a failure in middle of recovery! >:-)
          ansible.builtin.command: /bin/false

        - name: Never print this
          ansible.builtin.debug:
            msg: 'I also never execute :-('
      # Always executed. Like Finally block in python
      always:
        - name: Always do this
          ansible.builtin.debug:
            msg: "This always executes"
        - name: Make sure all handlers run
          meta: flush_handlers
        
  handlers:
    - name: Run me even after an error
      ansible.builtin.debug:
        msg: 'This handler runs even on error'