pipeline {
	agent none
	stages {
		stage('Maven') {
			agent {
				docker { image 'maven' }
			}
			steps {
				sh 'mvn --version'
			}
		}

		stage ('Node') {
			agent {
				docker { image 'node' }
			}
			steps {
				sh 'node --version'
			}
		}
	}
}
