-
  name: Deploy a web application
  hosts: agent-1
  tasks:
    - name: Install dependencies
      apt:
       state: present
       name: '{{ item }}'
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-mysqldb
